name: "CI setup"
runs:
  using: "composite"
  steps:
    - name: Install cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"

    - name: Install Dependencies
      run: .devcontainer/setup.sh
      shell: bash
