name: "CI checks"
runs:
  using: "composite"
  steps:
    - name: Build
      run: |
        for package in packages/*/; do
          (cd "$package" && pnpm build && pnpm install)
        done
        pnpm build:test
      shell: bash

    - name: ESLint
      run: pnpm lint --no-cache
      shell: bash
