name: "CI checks"
runs:
    using: "composite"
    steps:
        - name: Build
          run: |
              pnpm build:packages
              pnpm build:test
          shell: bash

        - name: ESLint
          run: pnpm lint --no-cache
          shell: bash
