name: "CI checks"
runs:
    using: "composite"
    steps:
        - name: Build
          run: |
              scripts/shell/ci-build.sh
          shell: bash

        - name: ESLint
          run: pnpm lint --no-cache
          shell: bash
