[package]
name = "transformer"
version = "0.1.0"
edition = "2024"

[dependencies]
dunce = "1.0.5"
full_moon = { version = "2.0.0", features = ["luau"] }
serde = "1.0.219"
serde_json = "1.0.143"
walkdir = "2.5.0"
