name: Release

on:
  push:
    branches:
      - main

env:
  CI: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  release:
    permissions:
      contents: write #  to create release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write #  to create pull request (changesets/action)

    if: github.repository == 'lisachandra/rbxts-xstate'

    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/checks

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build roblox asset files
        shell: bash
        run: |
          mkdir build
          for package in packages/*/; do
            package_name=$(jq -r .name "$package/package.json")
            rm -rf publish/src/node_modules
            pnpm add --filter publish --no-lockfile $package_name@workspace:^
            rojo sourcemap -o publish/sourcemap.json publish/default.project.json
            pnpm build:transform publish/src publish/sourcemap.json publish/src/include/RuntimeLib.luau
            rojo build -o "build/${package_name//\//-}.rbxm" publish/default.project.json
            pnpm remove --filter publish --no-lockfile $package_name
          done

      - name: Upload action artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
